module.exports = [
    // { title: "Support!!!",
    //     description: "Limor was the queen and ruler of support galaxy",
    //     instructions: "Destroy Jira and the open support tickets",
    //     victoryTitle: "Yes!!! the support week is over !!",
    //     victoryDescription: "You managed to close a lot of tickets! ",
    //     wave : [
    //     [1, "jira1"],
    //     [2, "jira2"],
    //     [3, "critical"],
    //     [4, "trivial"],
    //     [5, "major"],
    //     [6, "minor"],
    //     [7, "critical"],
    //     [8, "minor"],
    //     [9, "major"],
    //     [10, "trivial"]
    //   ] },
    { title: "No Honey!",
        description: "Honey is the most dangerous matter in the milky way",
        instructions: "Destroy the Honey and Free the universe from its eval side effects",
        wave : [
        [1, "honey1"],
        [3, "honey2"],
        [5, "honey3"],
        [7, "honey4"],
        // [9, "honey1"],
        // [13, "honey2"],
        // [13, "honey3"],
        // [16, "honey4"],
        // [18, "honey1"],
        // [20, "honey3"],
        // [24, "honey2"],
        // [24, "honey3"]
      ] },
    { title: "Devils Invasion",
        description: "House Devils are taking over Mars after defeating house Gang",
        instructions: "Defeat the best house in Yigal Alon 126",
      wave : [
        [1, "devil1"],
        [2, "meital"],
        [3, "royi"],
        [4, "devil2"],
        [5, "hadas"],
        [6, "noam"],
        [7, "devil3"],
        [8, "mark"],
        [9, "dima"],
        [10, "nitzan"]
      ] },
  { title: "The Hopper Era",
    description: "The Hopper house Era was the best Era in the bizzabo galaxy history",
    instructions: "All good things must end... Destroy them and make room for a new reign",
    wave : [
      [1, "hopper"],
      [2, "noam"],
      [3, "max"],
      [4, "dalit"],
      [5, "bunny1"],
      [6, "mark"],
      [7, "bunny2"],
      [8, "molev"]
    ] },
  { title: "The reign of house Ada",
        description: "House Ada has emerged and threatening to take over earth",
        instructions: "Take down House Ada and restore order to earth",
      wave : [
        [1, "ada"],
        [2, "liron"],
        [3, "guy"],
        [4, "essa"],
        [5, "muhamad"],
        [6, "ada"],
        [7, "zakkai"]
        // [8, "zakkai"]
      ] },
    { title: "Ticket Boost - the Big Bang",
      description: "Promote your galaxy to win the key to universe",
      instructions: "Kill it on social media to earn your reward",
      wave : [
        [1, "ticket"],
        [2, "facebook"],
        [3, "twitter"],
        [4, "share1"],
        [5, "like"],
        [6, "linkedin"],
        [7, "share2"]
      ] },
    { title: "Dehydrated lemon pie. Yummie!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [3, "zouro"],
        [7, "zouro"],
        [7, "trouo"],
        [8, "zouro"],
        [9, "trouo"],
        [12, "zouro"],
        [12, "zouro"],
        [12, "zouro"],
        [12, "zouro"],
        [15, "ouno"],
        [15, "ouno"],
      ] },
    { title: "There has been better holidays",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [2, "zouro"],
        [4, "zouro"],
        [4, "zouro"],
        [8, "zouro"],
        [8, "ouno"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [22, "trouo"],
        [22, "trouo"],
        [22, "trouo"],
        [22, "trouo"],
        [26, "ouno"],
        [26, "ouno"],
      ] },
    { title: "Born to beeee wiiiillldddd!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [6, "ouno"],
        [6, "ouno"],
        [7, "zouro"],
        [8, "zouro"],
        [9, "ouno"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "ouno"],
        [20, "zouro"],
        [20, "ouno"],
        [26, "douo"],
      ] },
    { title: "What is that funky smell?!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [6, "ouno"],
        [6, "ouno"],
        [7, "zouro"],
        [8, "zouro"],
        [10, "douo"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "ouno"],
        [20, "trouo"],
        [20, "trouo"],
        [20, "trouo"],
        [20, "trouo"],
        [24, "douo"],
        [26, "douo"],
        [26, "douo"],
      ] },

  ];

