module.exports = [
    // { title: "Support!!!",
    //     description: "Limor was the queen and ruler of support galaxy",
    //     instructions: "Destroy Jira and the open support tickets",
    //     victoryTitle: "Yes!!! the support week is over !!",
    //     victoryDescription: "You managed to close a lot of tickets! ",
    //     wave : [
    //     [1, "jira1"],
    //     [3, "jira2"],
    //     // [5, "jira1"],
    //     // [7, "jira2"],
    //     // [9, "jira3"],
    //     // [13, "jira1"],
    //     // [18, "jira2"],
    //     // [19, "jira3"],
    //     // [20, "jira1"],
    //     // [21, "jira3"]
    //   ] },
    { title: "No Honey!",
        description: "Limor had here share of allergic reactions to Honey while travelling through the milky way",
        instructions: "Destroy the Honey and Free the universe from its eval side effects",
        wave : [
        [1, "honey1"],
        [3, "honey2"],
        [5, "honey3"],
        [7, "honey4"],
        // [9, "honey1"],
        // [13, "honey2"],
        // [13, "honey3"],
        // [16, "honey4"],
        // [18, "honey1"],
        // [20, "honey3"],
        // [24, "honey2"],
        // [24, "honey3"]
      ] },
    { title: "I should not rest",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [3, "zouro"],
        [4, "zouro"],
        [8, "zouro"],
        [8, "zouro"],
        [8, "zouro"],
        [10, "zouro"],
        [14, "zouro"],
        [14, "zouro"],
        [19, "zouro"],
        [19, "zouro"],
        [19, "zouro"],
        [19, "zouro"]
      ] },
    { title: "New friends?",
      wave : [
        [1, "zouro"],
        [3, "zouro"],
        [8, "ouno"],
        [13, "zouro"],
        [13, "zouro"],
        [16, "zouro"],
        [18, "ouno"],
        [22, "zouro"],
        [22, "zouro"],
        [22, "zouro"],
        [26, "ouno"],
        [26, "ouno"]
      ] },
    { title: "Dehydrated lemon pie. Yummie!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [3, "zouro"],
        [7, "zouro"],
        [7, "trouo"],
        [8, "zouro"],
        [9, "trouo"],
        [12, "zouro"],
        [12, "zouro"],
        [12, "zouro"],
        [12, "zouro"],
        [15, "ouno"],
        [15, "ouno"],
      ] },
    { title: "There has been better holidays",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [2, "zouro"],
        [4, "zouro"],
        [4, "zouro"],
        [8, "zouro"],
        [8, "ouno"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [20, "zouro"],
        [22, "trouo"],
        [22, "trouo"],
        [22, "trouo"],
        [22, "trouo"],
        [26, "ouno"],
        [26, "ouno"],
      ] },
    { title: "Born to beeee wiiiillldddd!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [6, "ouno"],
        [6, "ouno"],
        [7, "zouro"],
        [8, "zouro"],
        [9, "ouno"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "ouno"],
        [20, "zouro"],
        [20, "ouno"],
        [26, "douo"],
      ] },
    { title: "What is that funky smell?!",
      wave : [
        [1, "zouro"],
        [2, "zouro"],
        [6, "ouno"],
        [6, "ouno"],
        [7, "zouro"],
        [8, "zouro"],
        [10, "douo"],
        [12, "zouro"],
        [16, "zouro"],
        [20, "zouro"],
        [20, "ouno"],
        [20, "trouo"],
        [20, "trouo"],
        [20, "trouo"],
        [20, "trouo"],
        [24, "douo"],
        [26, "douo"],
        [26, "douo"],
      ] },

  ];

